### ISSUE TITLE
feature request: view pairwise identities in MSA

### ISSUE THREAD

**Issue by tao-bioinfo** [msabrowser/msabrowser#11]
For example, assuming the first sequence is reference, showing identities of all the other sequences.

**Comment by furkanmtorun** [comment]
Dear @billzt ,

Thanks for using MSABrowser. 
Even though I am no longer participating in further development for MSABrowser, I believe collecting points from users would still be great for the bioinformaticians in the lab, if they are still interested in releasing a new version.

You are also more than welcome to submit PR to contribute so that lab staff might work on your PR directly!
So, it would be nice if you could elaborate on your request and/or contact them: You might have a look at the lab website for contact info: [KaplanLab.com Contact Page](http://kaplanlab.com/contact-us/)

Best,
Furkan
