### ISSUE TITLE
Add lowercase to colorSchemas

### ISSUE THREAD

**Issue by dreyes17** [msabrowser/msabrowser#9]
Hello,

first of all thank you very much for the msabrowser, it works very well! Nevertheless, I have seen a possible enhancement by adding lowercase letters to the colorSchemas. There are some alignment programs that output lowercase fasta files by default, such as MAFFT in the case you align nucleotides.

Best regards

**Comment by furkanmtorun** [comment]
Dear @dreyes17 ,

First of all, thank you very much for giving it a try on MSABrowser and your feedback is well appreciated.
Also, we are happy to hear that you like our tool!

As for your suggestion, we have added your input to our project plan and try to consider it during updates.
I think we could resolve this issue by converting all the inputs to uppercase rather than duplicating the keys in `ColorSchemas` dictionary.

Here is what I thought at Line 485 (https://github.com/thekaplanlab/msabrowser/blob/master/javascript/msabrowser.js#L485):

from 
```
 var aaLetter = seq1.charAt(positionIndex);
```

to 
```
 var aaLetter = seq1.charAt(positionIndex).toUpperCase();
```

What do you think @halilbilgin?

Yours sincerely,
Furkan

**Comment by furkanmtorun** [comment]
Dear @dreyes17,

Thank you very much again for informing us about the issue.
PR by @halilbilgin, as we discussed above, is on the way!

Best,
Furkan
